[tools]
"ubi:arduino/arduino-cli" = "latest"
"ubi:espressif/esptool" = "latest"

[vars]
chip = "esp8266"
board = "esp8266:esp8266:nodemcu"
sketch = "nodemcu.ino"

port = "/dev/ttyUSB0"
prog_baudrate = 1000000

[tasks.out_dir]
run = 'mkdir -p build/'
outputs = {auto = true}

[tasks.build]
depends = 'out_dir'
run = 'arduino-cli compile --quiet --fqbn {{vars.board}} --output-dir build {{vars.sketch}}'
sources = ['*.ino']
outputs = {auto = true}

[tasks.prog]
depends = 'build'
run = 'esptool --chip {{vars.chip}} -p {{vars.port}} -b {{vars.prog_baudrate}} --after soft_reset write_flash 0 build/*.bin'

[tasks.monitor]
run = 'arduino-cli monitor -q'

[tasks.clean]
run = 'rm build -rf'
